language: python
python:
  - "3.7"
cache: pip

addons:
  apt:
    packages: &common_packages
      - gfortran
      - libatlas-base-dev
      - liblapack-dev
      - libnetcdf-dev
      - libnetcdff-dev
      - eatmydata
      - ccache

install:
  - pip install -r requirements.txt
  - pip install sisl
  - pip install -e .
script:
  - pwd
  - cd examples/abinit-w90/SrMnO3
  - ls -lah
  - sh get_J.sh
